# Generated by Django 5.1.3 on 2025-01-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_cart_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
    ]
